### // GET ALL PROVINCES
GET http://localhost:3001/provinces HTTP/1.1


### // FILTER WINES BY PROVINCE
GET http://localhost:3001/Valle HTTP/1.1


### // SEARCH A WINE BY ID
GET http://localhost:3001/wines/df1f82f2-f601-47ad-9958-8cb1a9d81b02 HTTP/1.1


### // CREATE A WINE 
POST http://localhost:3001/wines HTTP/1.1
Content-Type: application/json

{
  "name": "Marian",
  "varietal": ["Blend"],
  "color_type": "White",
  "winery": "Argento",
  "price": 2000,
  "alcohol": 14,
  "volume": 600,
  "image": "https://www.espaciovino.com.ar/media/default/0001/65/thumb_64887_default_medium.jpeg",
  "stock": 10,
  "year": 2023,
  "province": "Valle",
  "region": "Guanajuato",
  "url": "https://www.google.com",
  "description": "Best mexican wine"
}

### // DELETE A WINE
DELETE http://localhost:3001/wines/c08b5b89-37e7-48ec-856f-1534255a222f HTTP/1.1


### // UPDATE A WINE
PUT http://localhost:3001/wines/df1f82f2-f601-47ad-9958-8cb1a9d81b02 HTTP/1.1
Content-Type: application/json

{
  "name": "Spanish Wine",
  "varietal": "Blend",
  "color_type": "White",
  "winery": "Argento",
  "price": 127,
  "alcohol": 14,
  "volume": 600,
  "image": "https://www.espaciovino.com.ar/media/default/0001/65/thumb_64887_default_medium.jpeg",
  "stock": 10,
  "year": 2023,
  "province": "Guanajuato",
  "region": "Mexico",
  "url": "https://www.google.com",
  "description": "Best mexican wine"
}

### // ORDER WINES BY PRICE ASCENDING /MIN/MAX
GET http://localhost:3001/orderAsc/price/0/2 HTTP/1.1


### // ORDER WINES BY PRICE DESCENDING /MIN/MAX
GET http://localhost:3001/orderDes/price/1/2 HTTP/1.1


### // GENERATE 10 RANDOM WINES OFFER
GET http://localhost:3001/offer/random HTTP/1.1

### // SEARCH ALL VARIETALS
GET http://localhost:3001/varietal/varietal HTTP/1.1

### // GENERAL ROUTER
GET http://localhost:3001/home/home HTTP/1.1